---
{% raw %}
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: "{% endraw %}{{ eda_webhook_port | default('5000') }}{% raw %}"

  rules:
    - name: New Edge Device Image
      condition: "'prod/rhde_image/production-image-definition.yml' in event.payload.commits[0].modified"
      action:
        run_workflow_template: 
          name: New Edge Device Image
          organization: "{{ event.payload.repository.owner.login  }} Organization"
          job_args:
            extra_vars:
              images_repo: "rhde"
              files_path: "prod/rhde_image"
              image_definition_file: "production-image-definition.yml"
              image_deploy_file: "production-deploy_version.yml"
              builder_blueprint_name: "production-{{ event.payload.repository.owner.login }}"
              image_environment: "prod"

    - name: Publish new production device image
      condition: "('prod/rhde_image/production-deploy_version.yml' in event.payload.commits[0].modified or 'prod/rhde_image/production-kickstart.ks' in event.payload.commits[0].modified) and 'prod/rhde_image/production-image-definition.yml' not in event.payload.commits[0].modified"
      action:
        run_job_template:
          name: Publish Image
          organization: "{{ event.payload.repository.owner.login  }} Organization"
          job_args:
            extra_vars:
              images_repo: "rhde"
              files_path: "prod/rhde_image"
              image_definition_file: "production-image-definition.yml"
              image_deploy_file: "production-deploy_version.yml"
              builder_blueprint_name: "production-{{ event.payload.repository.owner.login }}"
              image_environment: "prod"
              kickstart_name: "production-kickstart.ks"



    - name: Publish new test device image
      condition: "('prod/rhde_image/test-deploy_version.yml' in event.payload.commits[0].modified or 'prod/rhde_image/test-kickstart.ks' in event.payload.commits[0].modified) and 'prod/rhde_image/test-image-definition.yml' not in event.payload.commits[0].modified"
      action:
        run_job_template:
          name: Publish Image
          organization: "{{ event.payload.repository.owner.login  }} Organization"
          job_args:
            extra_vars:
              images_repo: "rhde"
              files_path: "test/rhde_image"
              image_definition_file: "test-image-definition.yml"
              image_deploy_file: "test-deploy_version.yml"
              builder_blueprint_name: "test-{{ event.payload.repository.owner.login }}"
              image_environment: "test"
              kickstart_name: "test-kickstart.ks"


    - name: Publish new dev device image
      condition: "('prod/rhde_image/dev-deploy_version.yml' in event.payload.commits[0].modified or 'prod/rhde_image/dev-kickstart.ks' in event.payload.commits[0].modified) and 'prod/rhde_image/dev-image-definition.yml' not in event.payload.commits[0].modified"
      action:
        run_job_template:
          name: Publish Image
          organization: "{{ event.payload.repository.owner.login  }} Organization"
          job_args:
            extra_vars:
              images_repo: "rhde"
              files_path: "dev/rhde_image"
              image_definition_file: "dev-image-definition.yml"
              image_deploy_file: "dev-deploy_version.yml"
              builder_blueprint_name: "dev-{{ event.payload.repository.owner.login }}"
              image_environment: "dev"
              kickstart_name: "dev-kickstart.ks"



    - name: Initial provisioning 
      condition: event.payload.ip_address is defined and event.payload.mac_address is defined and event.payload.user is defined
      action:
        run_workflow_template: 
          name: Provision Edge Device
          organization: "{{ event.payload.user }} Organization"
          job_args:
            extra_vars:
              user: "{{ event.payload.user }}"
              ip_address: "{{ event.payload.ip_address }}"
              mac_address: "{{ event.payload.mac_address }}"
              env: "{{ event.payload.env }}"
  execution_strategy: "parallel"
{% endraw %}
