---

- name: Check if firewalld is installed
  become: true
  shell: rpm -q firewalld  
  register: firewalld_installed
  ignore_errors: yes  

- name: Configure Firewall
  when: firewalld_installed.rc == 0
  block:
    - name: Install VPN required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3-firewall
        - libreswan


    - name: Open firewalld protocols for libreSwan
      become: true
      firewalld:
        rich_rule: "rule protocol value={{ item }} accept"
        permanent: true
        state: enabled
        immediate: yes
      with_items:
        - ah
        - esp

    - name: Open firewalld ports for libreSwan
      become: true
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      with_items:
        - 500/udp
        - 4500/udp

    - name: Reload firewalld
      become: true
      service:
        name: firewalld
        state: reloaded

