---
    - name: Open firewalld protocols for libreSwan
      become: true
      firewalld:
        rich_rule: "rule protocol value={{ item }} accept"
        permanent: true
        state: enabled
        immediate: yes
      with_items:
        - ah
        - esp

    - name: Open firewalld ports for libreSwan
      become: true
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      with_items:
        - 500/udp
        - 4500/udp

    - name: Reload firewalld
      become: true
      service:
        name: firewalld
        state: reloaded

    - name: Install VPN required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libreswan
