---

    - name: Get default gateway
      shell: ip route show default | awk '/default/ {print $3}'
      register: gateway_result

    - name: Get IP of interface used to reach default gateway
      shell: ip route get {{ gateway_result.stdout }} | awk '/src/ {print $7}'
      register: interface_result

    - name: Set private IP variable
      set_fact:
        aap_ip_private: "{{ interface_result.stdout }}"

    - name: Configure IPsec
      become: true
      template:
        src: "{{ vpn_ipsec_conf_file | default('../templates/ipsec.conf.j2') }}"
        dest: /etc/ipsec.conf

    - name: Configure libreSwan secrets
      become: true
      template:
        src: "{{ vpn_ipsec_secrets_file | default('../templates/ipsec.secrets.j2') }}"
        dest: /etc/ipsec.secrets

    - name: Start and enable ipsec server
      become: true
      service:
        name: ipsec
        state: restarted
        enabled: yes

