---

    - name: Generate server private key
      become: true
      shell: wg genkey
      register: server_private_key

    - name: Generate server public key
      become: true
      shell: echo "{{ server_private_key.stdout }}" | wg pubkey
      register: server_public_key

    - name: Configure WireGuard server
      become: true
      template:
        src: "{{ wireguard_server_conf_template }}"
        dest: "/etc/wireguard/server.conf"
      vars:
        server_public_key: "{{ server_public_key.stdout  }}"

    - name: Restart WireGuard
      become: true
      service:
        name: wg-quick@server.service
        state: restarted
